name: pcarpet-env

dependencies:
  - python=3.7
  - pip=20.0
  - ipython=7.12
  - numpy=1.18
  - scipy=1.4
  - matplotlib=3.1
  - pandas=1.0
  - scikit-learn=0.22
  - pip:
    - nibabel==3.1
    - pcarpet